#!/usr/bin/env bash

# MMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMddNMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMmhddMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMmddddmMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMNddddddNMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMNddddddddNMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMNddhhddhhddMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMdddddddddddmMMMMMMMMMMMMMM
# MMMMMMMMMMMMMmddddddddddddmMMMMMMMMMMMMM
# MMMMMMMMMMMMmdhhdhhhhddddddmMMMMMMMMMMMM
# MMMMMMMMMMMmdddhdhdhdhhhhhddmMMMMMMMMMMM
# MMMMMMMMMMmdddddddyoohdddddddmMMMMMMMMMM
# MMMMMMMMMmddhhhhdh-..:ddhdddddmMMMMMMMMM
# MMMMMMMMmdddddddyo+::ooydddddddNMMMMMMMM
# MMMMMMMmddddhhdd+......+ddddddddNMMMMMMM
# MMMMMMmddddddddyo::::::oyddddddddmMMMMMM
# MMMMMmddddddddd//+oooo++/dddddddddmMMMMM
# MMMMmddddmmNNNMMMMMMMMMMMMMNNmmddddmMMMM
# MMMmdmmNMMMMMMMMMMMMMMMMMMMMMMMMNNmdmMMM
# MNmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNM
# NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN

# zenlinux build script

# Author: Lucas Barbosa (llbarbosas)

# Packages
DIR="$(pwd)"
PKGS_DIR="$DIR/packages"
PKGS="$(ls $PKGS_DIR)"

# Build packages

for pkg in $PKGS; do
	cd $PKGS_DIR/$pkg && makepkg -sC
done

